#! /bin/bash
DOTFILES_DIR="$(cd "$(dirname "$0")" ; pwd -P)"

function macos {
    # install brew
    echo "install brew\n"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # replace upstream to tuna mirrors
    echo "replace brew upstream to tuna mirrors\n"
    cd "$(brew --repo)"
    git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

    cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
    git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
    brew update

    echo "install zsh\n"
    brew install zsh zsh-completions

    echo "set zsh as default shell\n"
    chsh -s $(which zsh)

    echo "install git\n"
    brew install git

    echo "install fonts\n"
    brew tap caskroom/fonts && brew cask install font-source-code-pro
    # install emacs
    echo "install emacs-plus\n"
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
    brew tap d12frosted/emacs-plus
    brew install emacs-plus
    ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications

    # install tmux
    brew install tmux --with-utf8proc
    tic -x -o ~/.terminfo ${DOTFILES_DIR}/xterm-24bit.terminfo
}

# install zsh
echo "install zsh\n"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

if [ "$(uname)" == "Darwin" ];then
    echo "install softwares for mac os\n"
    macos
fi

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# add node env
NVS_HOME="$HOME/.nvs"
echo "install nvs\n"
git clone https://github.com/jasongin/nvs "$NVS_HOME"
. "$NVS_HOME/nvs.sh" install
echo "install nvs done.\n"

echo "install node lts\n"
nvs add lts
echo "install node lts done.\n"

ln -sF $DOTFILES_DIR/.gitconfig .
ln -sF $DOTFILES_DIR/.tmux.conf .
