#! /bin/bash
DOTFILES_DIR=`pwd`

echo "install curl\n"
sudo apt-get install -y curl
echo "install curl done.\n"

echo "install nvm\n"
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
echo "install nvm done.\n"

echo "install node\n"
nvm install 0.11.13
nvm use 0.11.13
echo "install node done.\n"

[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

# Install jshint to allow checking of JS code within emacs
npm install -g jshint
# Install rlwrap to provide libreadline features with node
# See: Http://nodejs.org/api/repl.html#repl_repl
sudo apt-get install -y rlwrap
# Install tmux(using tmux insteal)
sudo apt-apt-repository -y ppa:pi-rho/dev
sudo apt-get -qq update
sudo apt-get install -y tmux=1.9a-1~ppa1~t
# Install emacs24
# https://launchpad.net/~cassou/+archive/emacs
sudo apt-add-repository -y ppa:cassou/emacs
sudo apt-get -qq update
sudo apt-get install -y emacs24-nox emacs24-el emacs24-common-non-dfsg

cd ~
ln -sb $DOTFILES_DIR/.screenrc .
ln -sb $DOTFILES_DIR/.bash_profile .
ln -sb $DOTFILES_DIR/.bashrc .
ln -sb $DOTFILES_DIR/.bashrc_custom .
ln -sb $DOTFILES_DIR/.gitconfig .
ln -sb $DOTFILES_DIR/.tmux.conf .
ln -sf $DOTFILES_DIR/.emacs.d .
ln -sf $DOTFILES_DIR/.bash-git-prompt .
ln -sf $DOTFILES_DIR/.fonts .

# Install fonts
fc-cache -fv
 
# install jenv
#curl -L -s get.jenv.io | bash
